name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
          submodules: true

      - name: Git Submodule Update
        run: git submodule update --remote --recursive
